version: '3.9'

services:
  vector-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-processor
    environment:
      KAFKA_TOPIC: vector.topic
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PGVECTOR_DSN: postgresql://postgres:postgres@pgvector:5432/scrapper
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
      POSTGRES_HOST: pgvector
    volumes:
      - ./src:/app/src
    working_dir: /app/src
    command: ["python", "-m", "main"]
    networks:
      - processor-net

  hashtag-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hashtag-processor
    environment:
      KAFKA_TOPIC: hashtag.topic
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PGVECTOR_DSN: postgresql://postgres:postgres@pgvector:5432/scrapper
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
      POSTGRES_HOST: pgvector
    volumes:
      - ./src:/app/src
    working_dir: /app/src
    command: ["python", "-m", "main"]
    networks:
      - processor-net

volumes:
  pgdata:

networks:
  processor-net:
    external: true