version: "3.9"

services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  postgres:
    image: ankane/pgvector
    container_name: pgvector
    restart: always
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper-consumer
    environment:
      KAFKA_TOPIC: scrapper.html.raw
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PGVECTOR_DSN: postgresql://postgres:postgres@pgvector:5432/scrapper
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - ./src:/app/src
    working_dir: /app/src
    depends_on:
      - kafka
      - postgres
    restart: always

volumes:
  pgdata: