services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - scrapper-net

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - scrapper-net

  postgres:
    image: ankane/pgvector
    container_name: pgvector
    restart: always
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scrapper-net

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper-consumer
    environment:
      KAFKA_TOPIC: vector.topic
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PGVECTOR_DSN: postgresql://postgres:postgres@pgvector:5432/scrapper
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - ./src:/app/src
    working_dir: /app/src
    depends_on:
      - kafka
      - postgres
    restart: always
    networks:
      - scrapper-net

volumes:
  pgdata:

networks:
  scrapper-net: